# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go_CI

on:
  push:
    branches: [ "main","development" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Install dependencies
      run: |
        go get .
        go get github.com/aws/aws-lambda-go
        go get github.com/aws/aws-sdk-go-v2
        go get github.com/aws/aws-sdk-go-v2/config
        go get github.com/aws/aws-sdk-go-v2/service/secretsmanager
        go get github.com/stretchr/testify
        go get go.mongodb.org/mongo-driver

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -json > TestResults-${{ matrix.go-version }}.json

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
