# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go_CI

on:
  push:
    branches: ["development"]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Install dependencies
      run: |
        go get github.com/aws/aws-lambda-go
        go get github.com/aws/aws-sdk-go-v2
        go get github.com/aws/aws-sdk-go-v2/config
        go get github.com/aws/aws-sdk-go-v2/service/secretsmanager
        go get github.com/stretchr/testify
        go get go.mongodb.org/mongo-driver
        go get github.com/golang-jwt/jwt/v5
        go get .

    - name: Run Tests
      run: go test -v ./...
